package com.crib.bills.dom6maps
package apps

import cats.effect.{ExitCode, IO, IOApp}
import cats.instances.either.*
import cats.syntax.all.*
import fs2.io.file.Path
import pureconfig.*

import java.nio.file.{Files as JavaFiles, Path as NioPath}

import apps.services.mapeditor.*
import apps.util.PathUtils
import model.map.{MapSize, WrapState}
import model.map.generation.{BorderSpecGenerationPolicy, GeometryGenerationInput, TerrainDistributionPolicy, TerrainImageVariantPolicy}

/**
 * CLI entry point that generates a new map set from a generator configuration file.
 *
 * Config file defaults to `map-generator.conf` and can be overridden with:
 * `-Ddom6.generator.configPath=/path/to/map-generator.conf`
 */
object MapGeneratorCliApp extends IOApp:
  type ErrorOr[A] = Either[Throwable, A]

  private val configFileName = "map-generator.conf"

  private def resolveConfigPath(): NioPath =
    sys.props
      .get("dom6.generator.configPath")
      .map(pathValue => PathUtils.normalizeForWSL(NioPath.of(pathValue)))
      .orElse {
        val cwd = NioPath.of(configFileName)
        if JavaFiles.exists(cwd) then Some(cwd) else None
      }
      .orElse {
        val parent = NioPath.of("..", configFileName).normalize()
        if JavaFiles.exists(parent) then Some(parent) else None
      }
      .getOrElse(NioPath.of(configFileName))

  private val sampleConfig =
    """output="C:/Users/Shadow's Throne/AppData/Roaming/Dominions6/maps/sample-map-bundle"
map-name="generated_example"
map-title="Generated Example"
map-description="Generated by MapGeneratorCliApp"

geometry {
  map-size=8
  province-count=80
  wrap-state="none"
  seed=42
  sea-ratio=0.30
  noise-scale=1.0
  grid-jitter=0.5
}

terrain-distribution {
  swamp-percent=0.07
  waste-percent=0.07
  highland-percent=0.06
  forest-percent=0.17
  farm-percent=0.15
  extra-lake-percent=0.07
}

terrain-images {
  policy="base-only"
}

underground {
  enabled=true
  plane-name="The Underworld"
  connect-every-province-with-tunnel=true
}

connection-borders {
  non-highland-river-percent=0.20
  non-highland-road-percent=0.20
  non-highland-bridged-river-percent=0.0
  highland-mountain-percent=0.30
  highland-mountain-pass-percent=0.20
  highland-road-percent=0.15
}
"""

  override def run(args: List[String]): IO[ExitCode] =
    val configPath = resolveConfigPath()

    val geometryGenerator = new GridNoiseMapGeometryGeneratorImpl[IO]
    val borderSpecService = new GeneratedBorderSpecServiceImpl
    val mapWriter = new MapWriterImpl[IO]
    val mapImageWriter = new MapImageWriterImpl[IO]
    val terrainVariants = new TerrainImageVariantServiceImpl[IO]
    val generationService = new MapGenerationServiceImpl[IO](
      geometryGenerator,
      borderSpecService,
      mapWriter,
      mapImageWriter,
      terrainVariants
    )

    for
      exists <- IO(JavaFiles.exists(configPath))
      _ <-
        if exists then IO.unit
        else
          IO(JavaFiles.writeString(configPath, sampleConfig)) *>
            IO.raiseError(RuntimeException(s"${configPath.getFileName.toString} created; please edit and rerun"))
      rawConfig <- IO(ConfigSource.file(configPath).loadOrThrow[MapGeneratorConfig])
      generationRequest <- IO.fromEither(toGenerationRequest(rawConfig))
      outputDirectory = Path.fromNioPath(PathUtils.normalizeForWSL(rawConfig.output))
      result <- generationService.generate[ErrorOr](generationRequest, outputDirectory)
      outputMapPath <- IO.fromEither(result)
      _ <- IO.println(s"Generated map set at: ${outputMapPath.parent.getOrElse(outputMapPath)}")
    yield ExitCode.Success

  private def toGenerationRequest(config: MapGeneratorConfig): Either[Throwable, MapGenerationRequest] =
    for
      mapSize <- MapSize.from(config.geometry.mapSize)
      wrapState <- parseWrapStateForTest(config.geometry.wrapState)
      terrainPolicy <- parseTerrainImagePolicyForTest(config.terrainImages.policy)
      terrainDistributionPolicy <- parseTerrainDistributionPolicyForTest(
        config.terrainDistribution.getOrElse(MapGeneratorTerrainDistributionConfig.default)
      )
      undergroundGenerationMode <- parseUndergroundGenerationModeForTest(
        config.underground.getOrElse(MapGeneratorUndergroundConfig.disabled)
      )
      borderPolicy <- parseBorderSpecGenerationPolicyForTest(
        config.connectionBorders.getOrElse(MapGeneratorConnectionBordersConfig.default)
      )
      seed = config.geometry.seed.getOrElse(0L)
    yield
      MapGenerationRequest(
        mapName = config.mapName,
        mapTitle = config.mapTitle,
        mapDescription = config.mapDescription,
        geometryInput = GeometryGenerationInput(
          mapSize = mapSize,
          provinceCount = config.geometry.provinceCount,
          wrapState = wrapState,
          seed = seed,
          seaRatio = config.geometry.seaRatio,
          noiseScale = config.geometry.noiseScale,
          gridJitter = config.geometry.gridJitter,
          terrainDistributionPolicy = terrainDistributionPolicy
        ),
        borderSpecGenerationPolicy = borderPolicy,
        terrainImageVariantPolicy = terrainPolicy,
        undergroundGenerationMode = undergroundGenerationMode
      )

  private[apps] def parseWrapStateForTest(value: String): Either[Throwable, WrapState] =
    value.trim.toLowerCase match
      case "none" | "nowrap" | "no-wrap" => Right(WrapState.NoWrap)
      case "hwrap" | "horizontal"         => Right(WrapState.HorizontalWrap)
      case "vwrap" | "vertical"           => Right(WrapState.VerticalWrap)
      case "full" | "fullwrap" | "full-wrap" => Right(WrapState.FullWrap)
      case other => Left(IllegalArgumentException(s"Unsupported wrapState value: $other"))

  private[apps] def parseTerrainImagePolicyForTest(value: String): Either[Throwable, TerrainImageVariantPolicy] =
    value.trim.toLowerCase match
      case "base-only" | "base" => Right(TerrainImageVariantPolicy.BaseOnly)
      case "base-and-winter" | "winter" => Right(TerrainImageVariantPolicy.BaseAndWinter)
      case "full" | "full-terrain-set" => Right(TerrainImageVariantPolicy.FullTerrainSet)
      case other => Left(IllegalArgumentException(s"Unsupported terrain image policy value: $other"))

  private[apps] def parseBorderSpecGenerationPolicyForTest(
      config: MapGeneratorConnectionBordersConfig
  ): Either[Throwable, BorderSpecGenerationPolicy] =
    BorderSpecGenerationPolicy.fromRaw[ErrorOr](
      nonHighlandRiverPercent = config.nonHighlandRiverPercent,
      nonHighlandRoadPercent = config.nonHighlandRoadPercent,
      nonHighlandBridgedRiverPercent = config.nonHighlandBridgedRiverPercent,
      highlandMountainPercent = config.highlandMountainPercent,
      highlandMountainPassPercent = config.highlandMountainPassPercent,
      highlandRoadPercent = config.highlandRoadPercent
    )

  private[apps] def parseTerrainDistributionPolicyForTest(
      config: MapGeneratorTerrainDistributionConfig
  ): Either[Throwable, TerrainDistributionPolicy] =
    TerrainDistributionPolicy.fromRaw[ErrorOr](
      swampPercent = config.swampPercent,
      wastePercent = config.wastePercent,
      highlandPercent = config.highlandPercent,
      forestPercent = config.forestPercent,
      farmPercent = config.farmPercent,
      extraLakePercent = config.extraLakePercent
    )

  private[apps] def parseUndergroundGenerationModeForTest(
      config: MapGeneratorUndergroundConfig
  ): Either[Throwable, UndergroundGenerationMode] =
    if !config.enabled then Right(UndergroundGenerationMode.Disabled)
    else if config.planeName.trim.isEmpty then Left(IllegalArgumentException("underground.planeName must not be empty"))
    else
      Right(
        UndergroundGenerationMode.MirroredPlane(
          planeName = config.planeName,
          connectEveryProvinceWithTunnel = config.connectEveryProvinceWithTunnel
        )
      )
