package com.crib.bills.dom6maps
package apps.services.mapeditor

import cats.effect.IO
import cats.instances.either.*
import fs2.io.file.Path
import java.nio.file.{Files => JavaFiles}
import model.map.{MapFileParser, MapSize, WrapState, ImageFile, NeighbourSpec, WinterImageFile, Pb}
import model.map.generation.{GeometryGenerationInput, TerrainImageVariantPolicy}
import weaver.SimpleIOSuite

object MapGenerationServiceSpec extends SimpleIOSuite:
  type ErrorOr[A] = Either[Throwable, A]

  test("generates map file and base image") {
    val service = new MapGenerationServiceImpl[IO](
      new GridNoiseMapGeometryGeneratorImpl[IO],
      new GeneratedBorderSpecServiceImpl,
      new MapWriterImpl[IO],
      new MapImageWriterImpl[IO],
      new TerrainImageVariantServiceImpl[IO]
    )

    val request = MapGenerationRequest(
      mapName = "generated_example",
      mapTitle = "Generated Example",
      mapDescription = Some("Generated by service"),
      geometryInput = GeometryGenerationInput(
        mapSize = MapSize.from(2).toOption.get,
        provinceCount = 10,
        wrapState = WrapState.NoWrap,
        seed = 18L,
        seaRatio = 0.3,
        noiseScale = 1.0,
        gridJitter = 0.5
      ),
      terrainImageVariantPolicy = TerrainImageVariantPolicy.BaseOnly
    )

    for
      outputDirectory <- IO(JavaFiles.createTempDirectory("map-generation-base"))
      result <- service.generate[ErrorOr](request, Path.fromNioPath(outputDirectory))
      outputMapPath <- IO.fromEither(result)
      directives <- MapFileParser.parseFile[IO](outputMapPath).compile.toVector
    yield expect.all(
      JavaFiles.exists(outputDirectory.resolve("generated_example.map")),
      JavaFiles.exists(outputDirectory.resolve("generated_example.tga")),
      directives.exists { case ImageFile("generated_example.tga") => true; case _ => false },
      directives.exists { case _: Pb => true; case _ => false },
      directives.exists { case _: NeighbourSpec => true; case _ => false }
    )
  }

  test("generates winter image directive and file when configured") {
    val service = new MapGenerationServiceImpl[IO](
      new GridNoiseMapGeometryGeneratorImpl[IO],
      new GeneratedBorderSpecServiceImpl,
      new MapWriterImpl[IO],
      new MapImageWriterImpl[IO],
      new TerrainImageVariantServiceImpl[IO]
    )

    val request = MapGenerationRequest(
      mapName = "generated_winter",
      mapTitle = "Generated Winter",
      mapDescription = None,
      geometryInput = GeometryGenerationInput(
        mapSize = MapSize.from(2).toOption.get,
        provinceCount = 10,
        wrapState = WrapState.NoWrap,
        seed = 21L,
        seaRatio = 0.3,
        noiseScale = 1.1,
        gridJitter = 0.5
      ),
      terrainImageVariantPolicy = TerrainImageVariantPolicy.BaseAndWinter
    )

    for
      outputDirectory <- IO(JavaFiles.createTempDirectory("map-generation-winter"))
      result <- service.generate[ErrorOr](request, Path.fromNioPath(outputDirectory))
      outputMapPath <- IO.fromEither(result)
      directives <- MapFileParser.parseFile[IO](outputMapPath).compile.toVector
    yield expect.all(
      directives.exists { case WinterImageFile("generated_winter_winter.tga") => true; case _ => false },
      JavaFiles.exists(outputDirectory.resolve("generated_winter_winter.tga"))
    )
  }
