package com.crib.bills.dom6maps
package apps.services.mapeditor

import cats.effect.IO
import cats.instances.either.*
import fs2.io.file.Path
import java.nio.file.{Files => JavaFiles}
import model.{BorderFlag, Nation, ProvinceId, TerrainFlag, TerrainMask}
import model.map.{AllowedPlayer, Commander, Feature, Gate, ImageFile, MapDirective, MapFileParser, MapSize, NeighbourSpec, Pb, PlaneName, ProvinceLocation, SetLand, SpecStart, Terrain, ThroneLevel, Units, WrapState, WinterImageFile, XCell, YCell}
import model.map.generation.{GeometryGenerationInput, PlayerStartAssignment, TerrainImageVariantPolicy}
import weaver.SimpleIOSuite

object MapGenerationServiceSpec extends SimpleIOSuite:
  type ErrorOr[A] = Either[Throwable, A]

  test("generates map file and base image") {
    val service = new MapGenerationServiceImpl[IO](
      new GridNoiseMapGeometryGeneratorImpl[IO],
      new GeneratedBorderSpecServiceImpl,
      new MapWriterImpl[IO],
      new MapImageWriterImpl[IO],
      new TerrainImageVariantServiceImpl[IO],
      new ThronePlacementServiceImpl[IO],
      new MapGenerationDiagnosticsWriterImpl[IO]
    )

    val request = MapGenerationRequest(
      mapName = "generated_example",
      mapTitle = "Generated Example",
      mapDescription = Some("Generated by service"),
      geometryInput = GeometryGenerationInput(
        mapDimensions = model.map.MapDimensions.square(MapSize.from(2).toOption.get),
        provinceCount = 10,
        wrapState = WrapState.NoWrap,
        seed = 18L,
        seaRatio = 0.3,
        noiseScale = 1.0,
        gridJitter = 0.5
      ),
      terrainImageVariantPolicy = TerrainImageVariantPolicy.BaseOnly
    )

    for
      outputDirectory <- IO(JavaFiles.createTempDirectory("map-generation-base"))
      result <- service.generate[ErrorOr](request, Path.fromNioPath(outputDirectory))
      outputMapPath <- IO.fromEither(result)
      directives <- MapFileParser.parseFile[IO](outputMapPath).compile.toVector
      bundleDirectory = outputDirectory.resolve("generated_example")
    yield expect.all(
      JavaFiles.exists(bundleDirectory.resolve("generated_example.map")),
      JavaFiles.exists(bundleDirectory.resolve("generated_example.tga")),
      directives.exists { case ImageFile("generated_example.tga") => true; case _ => false },
      directives.exists { case _: Pb => true; case _ => false },
      directives.exists { case _: NeighbourSpec => true; case _ => false }
    )
  }

  test("generates winter image directive and file when configured") {
    val service = new MapGenerationServiceImpl[IO](
      new GridNoiseMapGeometryGeneratorImpl[IO],
      new GeneratedBorderSpecServiceImpl,
      new MapWriterImpl[IO],
      new MapImageWriterImpl[IO],
      new TerrainImageVariantServiceImpl[IO],
      new ThronePlacementServiceImpl[IO],
      new MapGenerationDiagnosticsWriterImpl[IO]
    )

    val request = MapGenerationRequest(
      mapName = "generated_winter",
      mapTitle = "Generated Winter",
      mapDescription = None,
      geometryInput = GeometryGenerationInput(
        mapDimensions = model.map.MapDimensions.square(MapSize.from(2).toOption.get),
        provinceCount = 10,
        wrapState = WrapState.NoWrap,
        seed = 21L,
        seaRatio = 0.3,
        noiseScale = 1.1,
        gridJitter = 0.5
      ),
      terrainImageVariantPolicy = TerrainImageVariantPolicy.BaseAndWinter
    )

    for
      outputDirectory <- IO(JavaFiles.createTempDirectory("map-generation-winter"))
      result <- service.generate[ErrorOr](request, Path.fromNioPath(outputDirectory))
      outputMapPath <- IO.fromEither(result)
      directives <- MapFileParser.parseFile[IO](outputMapPath).compile.toVector
      bundleDirectory = outputDirectory.resolve("generated_winter")
    yield expect.all(
      directives.exists { case WinterImageFile("generated_winter_winter.tga") => true; case _ => false },
      JavaFiles.exists(bundleDirectory.resolve("generated_winter_winter.tga"))
    )
  }

  test("generates mirrored underground companion map and image when enabled") {
    val service = new MapGenerationServiceImpl[IO](
      new GridNoiseMapGeometryGeneratorImpl[IO],
      new GeneratedBorderSpecServiceImpl,
      new MapWriterImpl[IO],
      new MapImageWriterImpl[IO],
      new TerrainImageVariantServiceImpl[IO],
      new ThronePlacementServiceImpl[IO],
      new MapGenerationDiagnosticsWriterImpl[IO]
    )

    val request = MapGenerationRequest(
      mapName = "generated_pair",
      mapTitle = "Generated Pair",
      mapDescription = Some("Generated pair"),
      geometryInput = GeometryGenerationInput(
        mapDimensions = model.map.MapDimensions.square(MapSize.from(2).toOption.get),
        provinceCount = 10,
        wrapState = WrapState.NoWrap,
        seed = 31L,
        seaRatio = 0.3,
        noiseScale = 1.0,
        gridJitter = 0.5
      ),
      terrainImageVariantPolicy = TerrainImageVariantPolicy.BaseOnly,
      undergroundGenerationMode = UndergroundGenerationMode.MirroredPlane(
        planeName = "The Underworld",
        connectEveryProvinceWithTunnel = true
      ),
      throneGenerationMode = ThroneGenerationMode.RandomCorners(
        throneLevel = ThroneLevel(1),
        includeSurface = true,
        includeUnderground = true
      )
    )

    for
      outputDirectory <- IO(JavaFiles.createTempDirectory("map-generation-underground-pair"))
      result <- service.generate[ErrorOr](request, Path.fromNioPath(outputDirectory))
      outputMapPath <- IO.fromEither(result)
      surfaceDirectives <- MapFileParser.parseFile[IO](outputMapPath).compile.toVector
      bundleDirectory = outputDirectory.resolve("generated_pair")
      undergroundPath = bundleDirectory.resolve("generated_pair_plane2.map")
      undergroundDirectives <- MapFileParser.parseFile[IO](Path.fromNioPath(undergroundPath)).compile.toVector
      undergroundTerrains = undergroundDirectives.collect { case terrain: Terrain => terrain }
      undergroundHasFreshWater = undergroundTerrains.exists(terrain => (terrain.mask & TerrainFlag.FreshWater.mask) != 0L)
      undergroundHasMountains = undergroundTerrains.exists(terrain => (terrain.mask & TerrainFlag.Mountains.mask) != 0L)
      surfaceTerrains = surfaceDirectives.collect { case terrain: Terrain => terrain }
      surfaceThroneFeatures = countEncodedThroneFeatures(surfaceDirectives)
      undergroundThroneFeatures = countEncodedThroneFeatures(undergroundDirectives)
      surfaceThroneTerrains = surfaceTerrains.count(terrain => TerrainMask(terrain.mask).hasFlag(TerrainFlag.Throne))
      undergroundThroneTerrains = undergroundTerrains.count(terrain => TerrainMask(terrain.mask).hasFlag(TerrainFlag.Throne))
      surfaceBorderSpecs = surfaceDirectives.collect { case neighbourSpec: NeighbourSpec => neighbourSpec }
      borderFlagsByProvince = surfaceBorderSpecs.foldLeft(Map.empty[ProvinceId, Vector[BorderFlag]]) { (accumulator, neighbourSpec) =>
        val firstFlags = accumulator.getOrElse(neighbourSpec.a, Vector.empty) :+ neighbourSpec.border
        val secondFlags = accumulator.getOrElse(neighbourSpec.b, Vector.empty) :+ neighbourSpec.border
        accumulator.updated(neighbourSpec.a, firstFlags).updated(neighbourSpec.b, secondFlags)
      }
      surfaceFreshWaterRequiresRiver = surfaceTerrains.forall { terrain =>
        val terrainMask = TerrainMask(terrain.mask)
        !terrainMask.hasFlag(TerrainFlag.FreshWater) || borderFlagsByProvince
          .getOrElse(terrain.province, Vector.empty)
          .exists(flag => flag.includes(BorderFlag.River))
      }
      surfaceMountainRequiresImpassable = surfaceTerrains.forall { terrain =>
        val terrainMask = TerrainMask(terrain.mask)
        !terrainMask.hasFlag(TerrainFlag.Mountains) || borderFlagsByProvince
          .getOrElse(terrain.province, Vector.empty)
          .exists(flag => flag.includes(BorderFlag.Impassable))
      }
      undergroundAllHaveCaveFlag = undergroundTerrains.forall(terrain => (terrain.mask & TerrainFlag.Cave.mask) != 0L)
      undergroundHasSubtypeBits = undergroundTerrains.exists(terrain => terrain.mask != TerrainFlag.Cave.mask)
      undergroundHasAnySeaBits = undergroundTerrains.exists(terrain => (terrain.mask & TerrainFlag.Sea.mask) != 0L || (terrain.mask & TerrainFlag.DeepSea.mask) != 0L)
      surfaceGates = surfaceDirectives.collect { case gate: Gate => gate }
      undergroundGates = undergroundDirectives.collect { case gate: Gate => gate }
      hasAnySurfaceCave = surfaceDirectives.collect { case terrain: Terrain => terrain }.exists { terrain =>
        (terrain.mask & TerrainFlag.Cave.mask) != 0L || (terrain.mask & TerrainFlag.CaveWall.mask) != 0L
      }
    yield expect.all(
      JavaFiles.exists(bundleDirectory.resolve("generated_pair.map")),
      JavaFiles.exists(bundleDirectory.resolve("generated_pair.tga")),
      JavaFiles.exists(bundleDirectory.resolve("generated_pair_plane2.map")),
      JavaFiles.exists(bundleDirectory.resolve("generated_pair_plane2.tga")),
      undergroundDirectives.exists { case PlaneName("The Underworld") => true; case _ => false },
      undergroundTerrains.nonEmpty,
      surfaceThroneFeatures == 0,
      undergroundThroneFeatures == 0,
      surfaceThroneTerrains == 4,
      undergroundThroneTerrains == 4,
      surfaceFreshWaterRequiresRiver,
      surfaceMountainRequiresImpassable,
      undergroundAllHaveCaveFlag,
      undergroundHasSubtypeBits,
      !undergroundHasFreshWater,
      !undergroundHasMountains,
      !undergroundHasAnySeaBits,
      surfaceGates.nonEmpty,
      surfaceGates.forall(gate => gate.a == gate.b),
      undergroundGates.nonEmpty,
      undergroundGates.forall(gate => gate.a == gate.b),
      !hasAnySurfaceCave
    )
  }

  test("writes configured throne defender set pieces") {
    val service = new MapGenerationServiceImpl[IO](
      new GridNoiseMapGeometryGeneratorImpl[IO],
      new GeneratedBorderSpecServiceImpl,
      new MapWriterImpl[IO],
      new MapImageWriterImpl[IO],
      new TerrainImageVariantServiceImpl[IO],
      new ThronePlacementServiceImpl[IO],
      new MapGenerationDiagnosticsWriterImpl[IO]
    )

    val request = MapGenerationRequest(
      mapName = "generated_configured_setpiece",
      mapTitle = "Generated Configured Set Piece",
      mapDescription = Some("Configured throne set piece"),
      geometryInput = GeometryGenerationInput(
        mapDimensions = model.map.MapDimensions.square(MapSize.from(2).toOption.get),
        provinceCount = 10,
        wrapState = WrapState.NoWrap,
        seed = 77L,
        seaRatio = 0.3,
        noiseScale = 1.0,
        gridJitter = 0.5
      ),
      terrainImageVariantPolicy = TerrainImageVariantPolicy.BaseOnly,
      throneGenerationMode = ThroneGenerationMode.Configured(
        surfaceThrones = Vector(
          ConfiguredThronePlacementTarget(
            provinceId = None,
            location = Some(ProvinceLocation(XCell(0), YCell(0))),
            throneLevel = Some(ThroneLevel(1)),
            throneFeatureId = None
          )
        ),
        undergroundThrones = Vector.empty
      ),
      throneDefenderSetPieces = Vector(
        ThroneDefenderSetPiece(
          throneLevel = ThroneLevel(1),
          commanderType = "Indie Commander",
          units = Vector(ThroneDefenderUnit(20, "Militia"))
        )
      )
    )

    for
      outputDirectory <- IO(JavaFiles.createTempDirectory("map-generation-configured-setpiece"))
      result <- service.generate[ErrorOr](request, Path.fromNioPath(outputDirectory))
      outputMapPath <- IO.fromEither(result)
      directives <- MapFileParser.parseFile[IO](outputMapPath).compile.toVector
    yield expect.all(
      countEncodedThroneFeatures(directives) == 1,
      directives.exists { case Commander("Indie Commander") => true; case _ => false },
      directives.exists { case Units(20, "Militia") => true; case _ => false }
    )
  }

  test("writes allowed players on both layers and surface specstarts from nation starts") {
    val service = new MapGenerationServiceImpl[IO](
      new GridNoiseMapGeometryGeneratorImpl[IO],
      new GeneratedBorderSpecServiceImpl,
      new MapWriterImpl[IO],
      new MapImageWriterImpl[IO],
      new TerrainImageVariantServiceImpl[IO],
      new ThronePlacementServiceImpl[IO],
      new MapGenerationDiagnosticsWriterImpl[IO]
    )

    val request = MapGenerationRequest(
      mapName = "generated_nations",
      mapTitle = "Generated Nations",
      mapDescription = Some("Nation start directives"),
      geometryInput = GeometryGenerationInput(
        mapDimensions = model.map.MapDimensions.square(MapSize.from(2).toOption.get),
        provinceCount = 10,
        wrapState = WrapState.NoWrap,
        seed = 91L,
        seaRatio = 0.3,
        noiseScale = 1.0,
        gridJitter = 0.5
      ),
      terrainImageVariantPolicy = TerrainImageVariantPolicy.BaseOnly,
      undergroundGenerationMode = UndergroundGenerationMode.MirroredPlane(
        planeName = "The Underworld",
        connectEveryProvinceWithTunnel = true
      ),
      playerStarts = Vector(
        PlayerStartAssignment(Nation.Pythium_Middle, surfaceStart = Some(ProvinceId(3)), undergroundStart = None),
        PlayerStartAssignment(Nation.Sceleria_Middle, surfaceStart = Some(ProvinceId(8)), undergroundStart = None)
      )
    )

    for
      outputDirectory <- IO(JavaFiles.createTempDirectory("map-generation-nations"))
      result <- service.generate[ErrorOr](request, Path.fromNioPath(outputDirectory))
      outputMapPath <- IO.fromEither(result)
      surfaceDirectives <- MapFileParser.parseFile[IO](outputMapPath).compile.toVector
      bundleDirectory = outputDirectory.resolve("generated_nations")
      undergroundPath = bundleDirectory.resolve("generated_nations_plane2.map")
      undergroundDirectives <- MapFileParser.parseFile[IO](Path.fromNioPath(undergroundPath)).compile.toVector
    yield expect.all(
      surfaceDirectives.contains(AllowedPlayer(Nation.Pythium_Middle)),
      surfaceDirectives.contains(AllowedPlayer(Nation.Sceleria_Middle)),
      undergroundDirectives.contains(AllowedPlayer(Nation.Pythium_Middle)),
      undergroundDirectives.contains(AllowedPlayer(Nation.Sceleria_Middle)),
      surfaceDirectives.contains(SpecStart(Nation.Pythium_Middle, ProvinceId(3))),
      surfaceDirectives.contains(SpecStart(Nation.Sceleria_Middle, ProvinceId(8))),
      !undergroundDirectives.contains(SpecStart(Nation.Pythium_Middle, ProvinceId(3))),
      !undergroundDirectives.contains(SpecStart(Nation.Sceleria_Middle, ProvinceId(8)))
    )
  }

  private def countEncodedThroneFeatures(directives: Vector[MapDirective]): Int =
    directives.sliding(2).count {
      case Vector(_: SetLand, _: Feature) => true
      case _ => false
    }
