package com.crib.bills.dom6maps
package model

enum Nation(val id: Int, val epithet: String):
  // Early Era
  case Arcoscephale_Early extends Nation(5, "Golden Era")
  case Ermor_Early        extends Nation(6, "New Faith")
  case Ulm_Early          extends Nation(7, "Enigma of Steel")
  case Marverni_Early     extends Nation(8, "Time of Druids")
  case Sauromatia_Early   extends Nation(9, "Amazon Queens")
  case TienChi_Early      extends Nation(10, "Spring and Autumn")
  case Machaka_Early      extends Nation(11, "Lion Kings")
  case Mictlan_Early      extends Nation(12, "Reign of Blood")
  case Abysia_Early       extends Nation(13, "Children of Flame")
  case Pyrene_Early       extends Nation(14, "Kingdom of the Bekrydes")
  case CTis_Early         extends Nation(15, "Lizard Kings")
  case Pangaea_Early      extends Nation(16, "Age of Revelry")
  case Agartha_Early      extends Nation(17, "Pale Ones")
  case TirNaNog_Early     extends Nation(18, "Land of the Ever Young")
  case Ur_Early           extends Nation(19, "The First City")
  case Vanheim_Early      extends Nation(20, "Age of Vanir")
  case Helheim_Early      extends Nation(21, "Dusk and Death")
  case Niefelheim_Early   extends Nation(22, "Sons of Winter")
  case Kailasa_Early      extends Nation(25, "Rise of the Ape Kings")
  case Lanka_Early        extends Nation(26, "Land of Demons")
  case Yomi_Early         extends Nation(27, "Oni Kings")
  case Hinnom_Early       extends Nation(28, "Sons of the Fallen")
  case Fomoria_Early      extends Nation(29, "The Cursed Ones")
  case Berytos_Early      extends Nation(30, "Phoenix Empire")
  case Xibalba_Early      extends Nation(31, "Vigil of the Sun")
  case Atlantis_Early     extends Nation(36, "Emergence of the Deep Ones")
  case Rlyeh_Early        extends Nation(37, "Time of Aboleths")
  case Pelagia_Early      extends Nation(38, "Pearl Kings")
  case Oceania_Early      extends Nation(39, "Coming of the Capricorns")
  case Therodos_Early     extends Nation(40, "Telkhine Spectre")

  // Middle Era
  case Arcoscephale_Middle extends Nation(43, "The Old Kingdom")
  case Ermor_Middle        extends Nation(44, "Ashen Empire")
  case Sceleria_Middle     extends Nation(45, "Reformed Empire")
  case Pythium_Middle      extends Nation(46, "Emerald Empire")
  case Man_Middle          extends Nation(47, "Tower of Avalon")
  case Eriu_Middle         extends Nation(48, "Last of the Tuatha")
  case Ulm_Middle          extends Nation(49, "Forges of Ulm")
  case Marignon_Middle     extends Nation(50, "Fiery Justice")
  case Mictlan_Middle      extends Nation(51, "Reign of the Lawgiver")
  case TienChi_Middle      extends Nation(52, "Imperial Bureaucracy")
  case Machaka_Middle      extends Nation(53, "Reign of Sorcerors")
  case Agartha_Middle      extends Nation(54, "Golem Cult")
  case Abysia_Middle       extends Nation(55, "Blood and Fire")
  case Caelum_Middle       extends Nation(56, "Reign of the Seraphim")
  case CTis_Middle         extends Nation(57, "Miasma")
  case Pangaea_Middle      extends Nation(58, "Age of Bronze")
  case Asphodel_Middle     extends Nation(59, "Carrion Woods")
  case Vanheim_Middle      extends Nation(60, "Arrival of Man")
  case Jotunheim_Middle    extends Nation(61, "Iron Woods")
  case Vanarus_Middle      extends Nation(62, "Land of the Chuds")
  case BandarLog_Middle    extends Nation(63, "Land of the Apes")
  case Shinuyama_Middle    extends Nation(64, "Land of the Bakemono")
  case Ashdod_Middle       extends Nation(65, "Reign of the Anakim")
  case Uruk_Middle         extends Nation(66, "City States")
  case Nazca_Middle        extends Nation(67, "Kingdom of the Sun")
  case Xibalba_Middle      extends Nation(68, "Flooded Caves")
  case Atlantis_Middle     extends Nation(73, "Kings of the Deep")
  case Rlyeh_Middle        extends Nation(74, "Fallen Star")
  case Pelagia_Middle      extends Nation(75, "Triton Kings")
  case Oceania_Middle      extends Nation(76, "Mermidons")
  case Ys_Middle           extends Nation(77, "Morgen Queens")

  // Late Era
  case Arcoscephale_Late  extends Nation(80, "Sibylline Guidance")
  case Pythium_Late       extends Nation(81, "Serpent Cult")
  case Lemuria_Late       extends Nation(99, "Soul Gates")
  case Man_Late           extends Nation(83, "Towers of Chelms")
  case Ulm_Late           extends Nation(84, "Black Forest")
  case Marignon_Late      extends Nation(85, "Conquerors of the Sea")
  case Mictlan_Late       extends Nation(86, "Blood and Rain")
  case TienChi_Late       extends Nation(109, "Barbarian Kings")
  case Jomon_Late         extends Nation(89, "Human Daimyos")
  case Agartha_Late       extends Nation(90, "Ktonian Dead")
  case Abysia_Late        extends Nation(91, "Blood of Humans")
  case Caelum_Late        extends Nation(106, "Return of the Raptors")
  case CTis_Late          extends Nation(93, "Desert Tombs")
  case Pangaea_Late       extends Nation(94, "New Era")
  case Midgard_Late       extends Nation(95, "Age of Men")
  case Utgard_Late        extends Nation(96, "Well of Urd")
  case Bogarus_Late       extends Nation(97, "Age of Heroes")
  case Patala_Late        extends Nation(98, "Reign of the Nagas")
  case Gath_Late          extends Nation(99, "Last of the Giants")
  case Ragha_Late         extends Nation(100, "Dual Kingdom")
  case Xibalba_Late       extends Nation(101, "Return of the Zotz")
  case Atlantis_Late      extends Nation(106, "Frozen Sea")
  case Rlyeh_Late         extends Nation(107, "Dreamlands")
  case Erytheia_Late      extends Nation(108, "Kingdom of Two Worlds")

  // Special
  case Independents        extends Nation(0, "Independents")
  case SpecialIndependents extends Nation(2, "Special Independents")
