package com.crib.bills.dom6maps
package model

enum Nation(val id: Int, val epithet: String):
  // Early Era
  case Arcoscephale_Early extends Nation(5, "Golden Era")
  case Mekone_Early       extends Nation(6, "Brazen Giants")
  case Pangaea_Early      extends Nation(7, "Age of Revelry")
  case Ermor_Early        extends Nation(8, "New Faith")
  case Sauromatia_Early   extends Nation(9, "Amazon Queens")
  case Fomoria_Early      extends Nation(10, "The Cursed Ones")
  case TirNaNog_Early     extends Nation(11, "Land of the Ever Young")
  case Marverni_Early     extends Nation(12, "Time of Druids")
  case Ulm_Early          extends Nation(13, "Enigma of Steel")
  case Pyrene_Early       extends Nation(14, "Kingdom of the Bekrydes")
  case Agartha_Early      extends Nation(15, "Pale Ones")
  case Abysia_Early       extends Nation(16, "Children of Flame")
  case Hinnom_Early       extends Nation(17, "Sons of the Fallen")
  case Ubar_Early         extends Nation(18, "Kingdom of the Unseen")
  case Ur_Early           extends Nation(19, "The First City")
  case Kailasa_Early      extends Nation(20, "Rise of the Ape Kings")
  case Lanka_Early        extends Nation(21, "Land of Demons")
  case TienChi_Early      extends Nation(22, "Spring and Autumn")
  case Yomi_Early         extends Nation(23, "Oni Kings")
  case Caelum_Early       extends Nation(24, "Eagle Kings")
  case Mictlan_Early      extends Nation(25, "Reign of Blood")
  case Xibalba_Early      extends Nation(26, "Vigil of the Sun")
  case CTis_Early         extends Nation(27, "Lizard Kings")
  case Machaka_Early      extends Nation(28, "Lion Kings")
  case Berytos_Early      extends Nation(29, "The Phoenix Empire")
  case Vanheim_Early      extends Nation(30, "Age of Vanir")
  case Helheim_Early      extends Nation(31, "Dusk and Death")
  case Rus_Early          extends Nation(32, "Sons of Heaven")
  case Niefelheim_Early   extends Nation(33, "Sons of Winter")
  case Muspelheim_Early   extends Nation(34, "Sons of Fire")
  case Pelagia_Early      extends Nation(40, "Pearl Kings")
  case Oceania_Early      extends Nation(41, "Coming of the Capricorns")
  case Therodos_Early     extends Nation(42, "Telkhine Spectre")
  case Atlantis_Early     extends Nation(43, "Emergence of the Deep Ones")
  case Rlyeh_Early        extends Nation(44, "Time of Aboleths")

  // Middle Era
  case Arcoscephale_Middle extends Nation(50, "The Old Kingdom")
  case Phlegra_Middle      extends Nation(51, "Deformed Giants")
  case Pangaea_Middle      extends Nation(52, "Age of Bronze")
  case Asphodel_Middle     extends Nation(53, "Carrion Woods")
  case Ermor_Middle        extends Nation(54, "Ashen Empire")
  case Sceleria_Middle     extends Nation(55, "The Reformed Empire")
  case Pythium_Middle      extends Nation(56, "Emerald Empire")
  case Man_Middle          extends Nation(57, "Tower of Avalon")
  case Eriu_Middle         extends Nation(58, "Last of the Tuatha")
  case Agartha_Middle      extends Nation(59, "Golem Cult")
  case Ulm_Middle          extends Nation(60, "Forges of Ulm")
  case Marignon_Middle     extends Nation(61, "Fiery Justice")
  case Pyrene_Middle       extends Nation(62, "Time of the Akelarre")
  case Abysia_Middle       extends Nation(63, "Blood and Fire")
  case Ashdod_Middle       extends Nation(64, "Reign of the Anakim")
  case NaBa_Middle         extends Nation(65, "Queens of the Desert")
  case Uruk_Middle         extends Nation(66, "City States")
  case Ind_Middle          extends Nation(67, "Magnificent Kingdom of Exalted Virtue")
  case BandarLog_Middle    extends Nation(68, "Land of the Apes")
  case TienChi_Middle      extends Nation(69, "Imperial Bureaucracy")
  case Shinuyama_Middle    extends Nation(70, "Land of the Bakemono")
  case Caelum_Middle       extends Nation(71, "Reign of the Seraphim")
  case Nazca_Middle        extends Nation(72, "Kingdom of the Sun")
  case Mictlan_Middle      extends Nation(73, "Reign of the Lawgiver")
  case Xibalba_Middle      extends Nation(74, "Flooded Caves")
  case CTis_Middle         extends Nation(75, "Miasma")
  case Machaka_Middle      extends Nation(76, "Reign of Sorcerors")
  case Phaeacia_Middle     extends Nation(77, "Isle of the Dark Ships")
  case Vanheim_Middle      extends Nation(78, "Arrival of Man")
  case Vanarus_Middle      extends Nation(79, "Land of the Chuds")
  case Jotunheim_Middle    extends Nation(80, "Iron Woods")
  case Nidavangr_Middle    extends Nation(81, "Bear, Wolf and Crow")
  case Ys_Middle           extends Nation(85, "Morgen Queens")
  case Pelagia_Middle      extends Nation(86, "Triton Kings")
  case Oceania_Middle      extends Nation(87, "Mermidons")
  case Atlantis_Middle     extends Nation(88, "Kings of the Deep")
  case Rlyeh_Middle        extends Nation(89, "Fallen Star")

  // Late Era
  case Arcoscephale_Late  extends Nation(95, "Sibylline Guidance")
  case Phlegra_Late       extends Nation(96, "Sleeping Giants")
  case Pangaea_Late       extends Nation(97, "New Era")
  case Pythium_Late       extends Nation(98, "Serpent Cult")
  case Lemuria_Late       extends Nation(99, "Soul Gates")
  case Man_Late           extends Nation(100, "Towers of Chelms")
  case Ulm_Late           extends Nation(101, "Black Forest")
  case Agartha_Late       extends Nation(102, "Ktonian Dead")
  case Marignon_Late      extends Nation(103, "Conquerors of the Sea")
  case Abysia_Late        extends Nation(104, "Blood of Humans")
  case Ragha_Late         extends Nation(105, "Dual Kingdom")
  case Caelum_Late        extends Nation(106, "Return of the Raptors")
  case Gath_Late          extends Nation(107, "Last of the Giants")
  case Patala_Late        extends Nation(108, "Reign of the Nagas")
  case TienChi_Late       extends Nation(109, "Barbarian Kings")
  case Jomon_Late         extends Nation(110, "Human Daimyos")
  case Mictlan_Late       extends Nation(111, "Blood and Rain")
  case Xibalba_Late       extends Nation(112, "Return of the Zotz")
  case CTis_Late          extends Nation(113, "Desert Tombs")
  case Midgard_Late       extends Nation(115, "Age of Men")
  case Bogarus_Late       extends Nation(116, "Age of Heroes")
  case Utgard_Late        extends Nation(117, "Well of Urd")
  case Vaettiheim_Late    extends Nation(118, "Wolf Kin Jarldom")
  case Feminie_Late       extends Nation(119, "Sage-Queens")
  case Piconye_Late       extends Nation(120, "Legacy of the Prester King")
  case Andramania_Late    extends Nation(121, "Dog Republic")
  case Pyrene_Late        extends Nation(123, "Cambion Kings")
  case Zemaitia_Late      extends Nation(124, "Sylvan Knights")
  case Erytheia_Late      extends Nation(125, "Kingdom of Two Worlds")
  case Atlantis_Late      extends Nation(126, "Frozen Sea")
  case Rlyeh_Late         extends Nation(127, "Dreamlands")

  // Special
  case Independents        extends Nation(0, "Independents")
  case SpecialMonsters1    extends Nation(1, "Special Monsters")
  case SpecialMonsters2    extends Nation(2, "Special Monsters")
  case SpecialMonsters3    extends Nation(3, "Special Monsters")
  case SpecialMonsters4    extends Nation(4, "Special Monsters")

object Nation:
  val byId: Map[Int, Nation] = values.map(n => n.id -> n).toMap
